# customer = test.iloc[0].drop('id').to_dict()
customer = {"battery_power": 1043.0,
            "blue": 1.0,
            "clock_speed": 1.8,
            "dual_sim": 1.0,
            "fc": 14.0,
            "four_g": 0.0,
            "int_memory": 5.0,
            "m_dep": 0.1,
            "mobile_wt": 193.0,
            "n_cores": 3.0,
            "pc": 16.0,
            "px_height": 226.0,
            "px_width": 1412.0,
            "ram": 3476.0,
            "sc_h": 12.0,
            "sc_w": 7.0,
            "talk_time": 2.0,
            "three_g": 0.0,
            "touch_screen": 1.0,
            "wifi": 0.0}